version: "3.9"

services:
  redis:
    image: redis:7
    restart: unless-stopped

  web:
    build: .
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "80:8000"          # expone la API en el puerto 80 del VPS
    volumes:
      - ./media:/app/media
      - ./temp:/app/temp
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build: .
    command: celery -A celery_app.celery_app worker --loglevel=info --concurrency=3
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./media:/app/media
      - ./temp:/app/temp
    depends_on:
      - redis
    restart: unless-stopped


  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    command: npm run start -- -p 3000
    environment:
      # Esto es redundante con el ENV del Dockerfile, pero no estorba
      - NEXT_PUBLIC_BACKEND_URL=http://161.97.131.133:8000
    ports:
      - "3000:3000"
    depends_on:
      - web
    restart: unless-stopped
