version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./temp:/app/temp
    depends_on:
      - redis
    restart: unless-stopped
    # opcional, si el Dockerfile no tiene WORKDIR /app:
    # working_dir: /app

  worker:
    build: .
    command: celery -A celery_app.celery_app worker --loglevel=info --concurrency=1
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./media:/app/media
      - ./temp:/app/temp
    depends_on:
      - redis
    restart: unless-stopped
    # opcional:
    # working_dir: /app
